"""Init

Revision ID: 16526ca7bcf9
Revises: 
Create Date: 2025-03-25 21:06:39.560532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16526ca7bcf9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('db_name', sa.Text(), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('db_name', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('table_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mappings')
    op.drop_table('tables')
    # ### end Alembic commands ###
