"""Add mappings table

Revision ID: c2874dabc614
Revises: c0e77b1c2a9b
Create Date: 2025-03-22 11:14:37.190314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2874dabc614'
down_revision = 'c0e77b1c2a9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('db_name', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('table_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('table_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mappings')
    # ### end Alembic commands ###
